{
  "uid" : "41dd31d6750492f6",
  "name" : "test_main[cases53]",
  "fullName" : "test.test_api#test_main",
  "historyId" : "b2f97f7f0729796a83f8af9c30f43250",
  "time" : {
    "start" : 1641450353710,
    "stop" : 1641450353710,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: '/home/chenlei/backup_sqls/apiautotest_2022-01-06T14_21_46.sql'",
  "statusTrace" : "@pytest.fixture(scope=\"session\")\n    def data_clearing():\n        \"\"\"数据清洗\"\"\"\n        DataClearing.server_init()\n        # 1. 备份数据库\n>       DataClearing.backup_mysql()\n\ntest\\conftest.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntools\\data_clearing.py:119: in backup_mysql\n    cls.server.files_action(0,\ntools\\data_clearing.py:77: in files_action\n    self.ftp_client.get(remotepath=remote_path, localpath=file_path)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.sftp_client.SFTPClient object at 0x0000017F67AB25B0>\nremotepath = '/root/backup_sql/apiautotest_2022-01-06T14_21_46.sql'\nlocalpath = '/home/chenlei/backup_sqls/apiautotest_2022-01-06T14_21_46.sql'\ncallback = None\n\n    def get(self, remotepath, localpath, callback=None):\n        \"\"\"\n        Copy a remote file (``remotepath``) from the SFTP server to the local\n        host as ``localpath``.  Any exception raised by operations will be\n        passed through.  This method is primarily provided as a convenience.\n    \n        :param str remotepath: the remote file to copy\n        :param str localpath: the destination path on the local host\n        :param callable callback:\n            optional callback function (form: ``func(int, int)``) that accepts\n            the bytes transferred so far and the total bytes to be transferred\n    \n        .. versionadded:: 1.4\n        .. versionchanged:: 1.7.4\n            Added the ``callback`` param\n        \"\"\"\n>       with open(localpath, \"wb\") as fl:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/chenlei/backup_sqls/apiautotest_2022-01-06T14_21_46.sql'\n\nD:\\PythonCode\\apiAutoTest\\lib\\site-packages\\paramiko\\sftp_client.py:801: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "data_clearing",
    "time" : {
      "start" : 1641450353710,
      "stop" : 1641450354860,
      "duration" : 1150
    },
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: '/home/chenlei/backup_sqls/apiautotest_2022-01-06T14_21_46.sql'\n",
    "statusTrace" : "  File \"D:\\PythonCode\\apiAutoTest\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\PythonCode\\apiAutoTest\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\PythonCode\\apiAutoTest\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"F:\\CODE\\python-test\\apiAutoTest\\test\\conftest.py\", line 24, in data_clearing\n    DataClearing.backup_mysql()\n  File \"F:\\CODE\\python-test\\apiAutoTest\\tools\\data_clearing.py\", line 119, in backup_mysql\n    cls.server.files_action(0,\n  File \"F:\\CODE\\python-test\\apiAutoTest\\tools\\data_clearing.py\", line 77, in files_action\n    self.ftp_client.get(remotepath=remote_path, localpath=file_path)\n  File \"D:\\PythonCode\\apiAutoTest\\lib\\site-packages\\paramiko\\sftp_client.py\", line 801, in get\n    with open(localpath, \"wb\") as fl:\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: '/home/chenlei/backup_sqls/apiautotest_2022-01-06T14_21_46.sql'",
    "statusTrace" : "@pytest.fixture(scope=\"session\")\n    def data_clearing():\n        \"\"\"数据清洗\"\"\"\n        DataClearing.server_init()\n        # 1. 备份数据库\n>       DataClearing.backup_mysql()\n\ntest\\conftest.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntools\\data_clearing.py:119: in backup_mysql\n    cls.server.files_action(0,\ntools\\data_clearing.py:77: in files_action\n    self.ftp_client.get(remotepath=remote_path, localpath=file_path)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <paramiko.sftp_client.SFTPClient object at 0x0000017F67AB25B0>\nremotepath = '/root/backup_sql/apiautotest_2022-01-06T14_21_46.sql'\nlocalpath = '/home/chenlei/backup_sqls/apiautotest_2022-01-06T14_21_46.sql'\ncallback = None\n\n    def get(self, remotepath, localpath, callback=None):\n        \"\"\"\n        Copy a remote file (``remotepath``) from the SFTP server to the local\n        host as ``localpath``.  Any exception raised by operations will be\n        passed through.  This method is primarily provided as a convenience.\n    \n        :param str remotepath: the remote file to copy\n        :param str localpath: the destination path on the local host\n        :param callable callback:\n            optional callback function (form: ``func(int, int)``) that accepts\n            the bytes transferred so far and the total bytes to be transferred\n    \n        .. versionadded:: 1.4\n        .. versionchanged:: 1.7.4\n            Added the ``callback`` param\n        \"\"\"\n>       with open(localpath, \"wb\") as fl:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/home/chenlei/backup_sqls/apiautotest_2022-01-06T14_21_46.sql'\n\nD:\\PythonCode\\apiAutoTest\\lib\\site-packages\\paramiko\\sftp_client.py:801: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "49e5b250cab6d463",
      "name" : "stderr",
      "source" : "49e5b250cab6d463.txt",
      "type" : "text/plain",
      "size" : 1184
    } ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "flaky(reruns=2, reruns_delay=1)"
  }, {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "test_api"
  }, {
    "name" : "host",
    "value" : "DESKTOP-BNVFIE4"
  }, {
    "name" : "thread",
    "value" : "23664-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.test_api"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "cases",
    "value" : "['c55', '指标统计', '{\"Authorization\": \"${token}\"}', 'statusStat/StatCount', 'get', 'params', '', '{\"ip\":\"${iptoint(\"${ip}\")}\", \"serviceName\":\"${servicename}\", \"port\":\"${port}\", \"infoType\":4}', '', '', '{\"$.code\": 0}']"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "flaky(reruns=2, reruns_delay=1)" ]
  },
  "source" : "41dd31d6750492f6.json",
  "parameterValues" : [ "['c55', '指标统计', '{\"Authorization\": \"${token}\"}', 'statusStat/StatCount', 'get', 'params', '', '{\"ip\":\"${iptoint(\"${ip}\")}\", \"serviceName\":\"${servicename}\", \"port\":\"${port}\", \"infoType\":4}', '', '', '{\"$.code\": 0}']" ]
}